[package]
name = "__3"
version = "0.1.0"
authors = ["David Miller <david@orangetronic.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.12"